# Generated by Django 4.2.28 on 2026-02-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SprintSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_sprint_id', models.CharField(max_length=64)),
                ('sprint_name', models.CharField(max_length=255)),
                ('sprint_state', models.CharField(max_length=64)),
                ('sync_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sync_timestamp'],
                'indexes': [models.Index(fields=['jira_sprint_id', 'sync_timestamp'], name='compliance__jira_sp_9914b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EpicSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_issue_id', models.CharField(max_length=64)),
                ('jira_key', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=500)),
                ('status_name', models.CharField(max_length=128)),
                ('resolution_name', models.CharField(blank=True, max_length=128)),
                ('is_done', models.BooleanField(default=False)),
                ('jira_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='compliance.sprintsnapshot')),
                ('teams', models.ManyToManyField(blank=True, related_name='epic_snapshots', to='compliance.team')),
            ],
            options={
                'ordering': ['jira_key'],
            },
        ),
        migrations.CreateModel(
            name='DoDTaskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_issue_id', models.CharField(max_length=64)),
                ('jira_key', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('status_name', models.CharField(max_length=128)),
                ('resolution_name', models.CharField(blank=True, max_length=128)),
                ('is_done', models.BooleanField(default=False)),
                ('has_evidence_link', models.BooleanField(default=False)),
                ('evidence_link', models.URLField(blank=True)),
                ('non_compliance_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('epic_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dod_tasks', to='compliance.epicsnapshot')),
            ],
            options={
                'ordering': ['jira_key'],
            },
        ),
        migrations.CreateModel(
            name='NudgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(max_length=255)),
                ('recipient_emails', models.JSONField(default=list)),
                ('message_preview', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('epic_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_logs', to='compliance.epicsnapshot')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.team')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='compliance__sent_at_66737b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='epicsnapshot',
            index=models.Index(fields=['jira_key'], name='compliance__jira_ke_2d83f8_idx'),
        ),
        migrations.AddIndex(
            model_name='epicsnapshot',
            index=models.Index(fields=['is_done'], name='compliance__is_done_b5b86a_idx'),
        ),
        migrations.AddConstraint(
            model_name='epicsnapshot',
            constraint=models.UniqueConstraint(fields=('sprint_snapshot', 'jira_issue_id'), name='uniq_epic_snapshot_per_sprint_issue'),
        ),
        migrations.AddIndex(
            model_name='dodtasksnapshot',
            index=models.Index(fields=['category'], name='compliance__categor_d2bc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='dodtasksnapshot',
            index=models.Index(fields=['is_done', 'has_evidence_link'], name='compliance__is_done_2e7f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='dodtasksnapshot',
            constraint=models.UniqueConstraint(fields=('epic_snapshot', 'jira_issue_id'), name='uniq_dod_task_snapshot_per_epic_issue'),
        ),
    ]
