# Generated by Django 4.2.28 on 2026-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notification_emails',
            field=models.JSONField(default=list),
        ),
    ]
