# Generated by Django 4.2.28 on 2026-02-10 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_team_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scrum_masters',
            field=models.ManyToManyField(blank=True, related_name='managed_squads', to=settings.AUTH_USER_MODEL),
        ),
    ]
