# Generated by Django 4.2.28 on 2026-02-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_team_scrum_masters"),
    ]

    operations = [
        migrations.AddField(
            model_name="dodtasksnapshot",
            name="jira_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="epicsnapshot",
            name="missing_squad_labels",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="epicsnapshot",
            name="squad_label_warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sprintsnapshot",
            name="issue_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
