# Generated by Django 4.2.28 on 2026-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=16)),
                ('trigger', models.CharField(default='manual', max_length=32)),
                ('triggered_by', models.CharField(blank=True, max_length=255)),
                ('project_key', models.CharField(blank=True, max_length=64)),
                ('sprint_snapshots', models.IntegerField(default=0)),
                ('epic_snapshots', models.IntegerField(default=0)),
                ('dod_task_snapshots', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='jira_sync_s_started_2a9a8c_idx'), models.Index(fields=['status'], name='jira_sync_s_status_61d0bc_idx')],
            },
        ),
    ]
